---
title: "R Notebook"
output: html_notebook
---

# 1) Basics

Load the data

```{r}
url <- "https://raw.githubusercontent.com/kjytay/misc/master/data/epl_standings.csv"

epl_data <- read.csv(url)
```

Save the data in the project folder

```{r}
write.csv(epl_data, file = "epl_data.csv")
```

Load the libraries and set the theme

```{r}
library(tidyverse)
theme_set(theme_bw())
```

# Basic EDA

```{r}
View(epl_data)
```


```{r}
library(ggridges)
ggplot(epl_data, aes(x = Points, y = factor(Season))) +
    geom_density_ridges(scale = 3) +
    labs(y = "Season")
```


```{r}
ggplot(epl_data, aes(x = factor(Season), y = Points, group = Season)) +
    geom_boxplot() +
    labs(title = "Distribution of points by season")

```

```{r}
ggplot(epl_data, aes(x = reorder(Club, Points), y = Points, group = Club)) +
    geom_boxplot() +
    labs(title = "Distribution of clubs by points earned \nbetween 2008 and 2019") + 
    coord_flip()
```

```{r}
ggplot(epl_data, aes(x = reorder(Club, desc(Rank)), y = Rank, group = Club)) +
    geom_boxplot() +
    labs(title = "Distribution of clubs by rank achieved \nbetween 2008 and 2019") + 
    coord_flip()
```


```{r}
# plot of maximum and minimum
epl_data %>% group_by(Season) %>%
    summarize(max = max(Points), min = min(Points)) %>%
    mutate(range = max - min) %>%
    pivot_longer(max:range) %>%
    ggplot(aes(x = Season, y = value, col = name)) +
    geom_line() +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE) +
    scale_x_continuous(breaks = seq(min(epl_data$Season), max(epl_data$Season), by = 2)) +
    labs(title = "Max/min points by season", y = "Points") +
    theme(legend.title = element_blank(), legend.position = "bottom")


```


```{r}
epl_data %>% group_by(Season) %>%
    summarize(var = var(Points)) %>%
    ggplot(aes(x = Season, y = var)) +
    geom_line() +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE) +
    scale_x_continuous(breaks = seq(min(epl_data$Season), max(epl_data$Season), by = 2)) +
    labs(title = "Variance of point distribution by season", y = "Variance")

```


```{r}
max_var_dist <- seq(0, 38 * 3, by = 6)
max_var <- var(max_var_dist)
epl_data %>% group_by(Season) %>%
    summarize(var = var(Points)) %>%
    ggplot(aes(x = Season, y = var)) +
    geom_line() +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE) +
    geom_hline(yintercept = c(0, max_var), col = "red", linetype = "dashed") +
    scale_x_continuous(breaks = seq(min(epl_data$Season), max(epl_data$Season), by = 2)) +
    labs(title = "Variance of point distribution by season", y = "Variance")

```


```{r}

```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

